### ISSUE TITLE
Test7 fails

### ISSUE THREAD

**Issue by jwbos** [IACR/latex#112]
Test7 fails on my machine (Ubuntu 22.04.1 LTS). 

>       assert output[7] == 'å and Å  ü \\T1\\i \\T1\\DJ ' # note bad encoding
E       AssertionError: assert 'å and \x92 ü \\T1\\i \\T1\\DJ ' == 'å and Å\xa0 ü \\T1\\i \\T1\\DJ '
E         - å and Å  ü \T1\i \T1\DJ 
E         ?       ^^
E         + å and  ü \T1\i \T1\DJ 
E         ?       ^
compile_tests.py:198: AssertionError

**Comment by kmccurley** [comment]
Maybe this is because of python picking up a default character set either from your LOCALE or from venv or from your terminal. What do you see for LANG when you type `export` in a shell? I see
`declare -x LANG="en_US.UTF-8"`

**Comment by jwbos** [comment]
I (also) get:
`echo $LANG`
`en_US.UTF-8`

**Comment by kmccurley** [comment]
This is a complete mystery to me. The test was mostly an assertion of why we can't use pdflatex, so we need to track this down. Things to investigate include:
1. the encoding of the python file itself should default to UTF-8 according to PEP 263, but we can assert it with a comment at the beginning of the file.
2. we should inspect locale.getpreferredencoding() on your machine
3. we should try changing 'iso_8859_1' to 'latin-1' (with a dash) or 'latin-8895-1' with dashes instead of underscores.

**Comment by kmccurley** [comment]
Can you please try inserting
``
print(':'.join(hex(ord(char)) for char in output[7]))
```
at line 198 so we can see what the bytes are in output[7]?

**Comment by kmccurley** [comment]
Can you tell me what tex distribution you have on the machine? try using `latex --version`

**Comment by kmccurley** [comment]
I see something different (with bytes `0xc5:0xa0` instead of your `0x92`)
```
0xe5:0x20:0x61:0x6e:0x64:0x20:0xc5:0xa0:0x20:0xfc:0x20:0x5c:0x54:0x31:0x5c:0x69:0x20:0x5c:0x54:0x31:0x5c:0x44:0x4a:0x20
```
The actual UTF-8 encoding of the letter Š is 0xc5:0xa0. When you decode those bytes as iso8859_1, the first byte c5 would give  Å and 0x0a would give a non-breaking space so that's clearly not correct.

The more I think about this test the more I think we are testing the wrong thing. The example in our paper shows that pdflatex will produce mixed encodings in \write, and that's the point of what we should test for. When we force python to parse it as iso8859_1, it will fail because the input isn't encoded that way. The fact that it fails in different ways on our two machines must mean that something about the environment is causing python to guess wrong in the decoding.

I also think in fairness we should have \usepackage[utf8]{inputenc} in these files when sent to pdflatex. I'll have to think more about what we want to test here.
