### ISSUE TITLE
Line separation in enumerate

### ISSUE THREAD

**Issue by jwbos** [IACR/latex#158]
One user observed that line separation in enumerate and the description environments is very wide. Perhaps add [noitemsep] as default here.

**Comment by kmccurley** [comment]
These are inherited from the default line separations in article.cls. Note that authors have learned to squeeze things down because of page limits. I think we should resist such temptations, because the extra whitespace from the default class improves readability. I would prefer that if an author really demands tight spacing, they should use [this package](https://ctan.org/pkg/enumitem) to change the defaults, but we should leave the defaults as they are because they look better.

Whitespace is a common theme in publishing, and has been [studied extensively](https://www.scirp.org/html/27-1762433_91299.htm). I am more inclined to take common wisdom on the subject rather than mathematicians who have been trained to cram as much on a page as possible.

**Comment by kmccurley** [comment]
There is also a primitive `list` environment in LaTeX that can be used to construct any kind of list that people want.

**Comment by jwbos** [comment]
Agreed, I am hesitant to change the LaTeX default. Let's close this issue.
