### ISSUE TITLE
Issues with mmap

### ISSUE THREAD

**Issue by jwbos** [IACR/latex#167]
The following example:

```
\documentclass{iacrcc}
\usepackage{mmap}

\title{Problem}
\addauthor{Joppe W. Bos}
\addaffiliation{NXP Semiconductors}

\begin{document}
\maketitle
\begin{abstract}
  Abstract goes here. $\delta$ function, unit impulse
\end{abstract}
\end{document}
```
throws the cryptic error:
```
Runaway argument?
ot1lmrmn@cm@!edef cmap@f@encoding {this@f@enCoding }fi else ifx cmap@f@encoding
 ETC.
! File ended while scanning use of strip@CM@prefix@.
```
Do we need to support mmap?

**Comment by kmccurley** [comment]
It turns out that the following related example fails and it uses acmart instead of iacrcc. 
```
\documentclass{acmart}
\usepackage{mmap}

\title{Problem}
\author{Joppe W. Bos}
%\addaffiliation{NXP Semiconductors}

\begin{document}
\maketitle
\begin{abstract}
  Abstract goes here. $\delta$ function, unit impulse
\end{abstract}
\end{document}
```
It should come as no surprise that this is specific to pdflatex, since it works with lualatex. From this evidence I conclude that the problem is really with `mmap`, and we should not support it. It's relatively easy to check if it's loaded at the end of the preamble and fail with an error message.

**Comment by kmccurley** [comment]
We could also just put out a warning `\AtEndPreamble` if the package is loaded, but to be honest this doesn't seem like our problem to fix mmap. I suspect it's a conflict with hyperxmp, and I'm not convinced that we will continue to use it. Both packages are battling it out over how PDF metadata is encoded, and neither one seems to be robust.
