### ISSUE TITLE
Extend addfunding functionality

### ISSUE THREAD

**Issue by jwbos** [IACR/latex#226]
There is a feature request to extend the functionality of the `\addfunding` macro. 
Currently, this macro does not automatically create footnotes or an acknowledgements section: it only collects the metadata for indexing. This is done using the optional arguments: `fundref`, `ror`, `country`, and `grantid`. 
This leaves the responsibilities to the authors to define the exact / specific funding text and the location of their choice.

The feature request is to optionally change this. This means adding an optional argument `text` such as:

```
\addfunding[fundref=100018693,
            grantid={ H2020-ICT-2014-1 644209}
            country={European Union},
            text={This work was supported by the European Commission under the ICT programme with contract H2020-ICT-2014-1 644209 HEAT.}
           ]{HORIZON EUROPE Framework Programme}
```

This text can then also be used on the webpage of the accepted paper in the CiC.
Note that providing this option is optional: if an author does not want to use this feature this is of course fine. 

Some questions:

- Where to display this text? Typical places are in a footnote on the title page or in a separate acknowledgement section. 
- If this is done in the acknowledgement section, how can an author add his own text to extend this section?
- What if two funding sources are referenced? Should we let the authors create the correct single sentence in one macro invocation? Concatenate the two in the order we receive them?

**Comment by kmccurley** [comment]
I spent a couple of hours reading and thinking about this today. I think we're trying to balance several things here:
1. report funding to crossref in a structured format so that funding agencies can quickly find the research they published.
2. make it easy for authors to list their funding in a reasonably consistent way.
3. make it easy for authors to comply with any specific demands from their funding agency about wording in case the default does not fulfill the requirement.
4. provide transparency on who funded the research.

Our macros were designed only to satisfy 1. Authors may ignore it if they don't see anything in the PDF. If we don't display who funded the work in the PDF and the HTML, then we are ignoring 2 and 4. Some journals (e.g., PLOS) are very fussy about disclosing funding in order to expose potential conflicts of interest (e.g., research funded by Google that attacks Microsoft Windows). This is prominent in some fields like health, where [90% of journals require disclosure](https://bmcpublichealth.biomedcentral.com/articles/10.1186/s12889-018-5456-z), but is also relevant for any adversarial computer science or topics in which money is at stake.

There is no established standard for how to disclose funding. Part of my thinking is guided by the way that the funding information is reported to crossref, and in that case funding is associated to the _paper_ rather than the author. I think the reason may be that it's common for multiple authors to have the same funding, and there is no need for them to individually thank their funding agency. For this reason I don't think they should automatically be a footnote on the author, but authors can do this with our footnote mechanism.

In order to satisfy 2, 3, and 4, I propose that we generate an automatic section at the end of the paper (or a footnote) that looks like what the UK Research Information Network [suggested](https://www.ukri.org/wp-content/uploads/2020/10/RIN-251020-FundersAcknowledgementInScholarlyjournalArticles.pdf): 
![image](https://github.com/IACR/latex/assets/14105363/a9fe37ae-2675-4fe0-bbbf-3eff7eab97c7)
This is easy to generate in LaTeX (note that the listing for Intel does not have a grant ID). It could also be a footnote on the first page, but that might get crowded (maybe that's not a problem).  If this does not comply with what funding agencies require, the author could use a `\nofundingstatement` macro to disable it (it would then be up to the author to write an acknowledgements section). If the author uses `\nofundingstatement` then we would not produce the automatic section, but if the author does nothing other than use `\addfunding`, then the Funding acknowledgement would be generated automatically. Note that on anonymous submissions this section would not appear at all.

It has been observed that some funding agencies are finicky about how they want to be acknowledged, but that seems to be true in only a few cases (e.g,. NIH and Horizon Europe).  I spent a couple of hours looking at the guidelines from several funding agencies (e.g, [NSF](https://www.nsf.gov/pubs/gpg/nsf04_23/6.jsp#:~:text=An%20acknowledgment%20of%20NSF%20support,Science%20Foundation%20under%20Grant%20No.), [DoE](https://science.osti.gov/Funding-Opportunities/Acknowledgements#:~:text=For%20work%20supported%20by%20the,of%20Basic%20Energy%20Sciences), Horizon Europe (see below), [ARC in Australia](https://www.arc.gov.au/acknowledging-arc#:~:text=Acceptable%20Forms%20for%20Acknowledgement%20of%20ARC%20Funding&text=The%20acknowledgement%20should%20include%20the,Project%20ID%20must%20be%20included.) and [Canada NSERC](https://www.nserc-crsng.gc.ca/NSERC-CRSNG/acknowledgement_and_logos-mention_et_logos/index_eng.asp). I can only guess what Israel, Germany, Japan, or China require since their instructions were not in English. Most of the funding agencies give only general guidelines, and the same is true of publishers. 

The EU has by far the [most complicated guidelines](https://rea.ec.europa.eu/communicating-about-your-eu-funded-project_en), which I suspect will almost never be followed (they suggest inserting the flag into the paper. Seriously. 🤡) I went looking on arxiv to see if anyone funded by them actually displayed the flag and could not find a single one. [This paper](https://arxiv.org/pdf/2109.10638.pdf) was written by someone at the EU and still didn't follow the flag guidelines. Here are some others: [1](https://arxiv.org/pdf/2312.09383.pdf) [2](https://arxiv.org/pdf/2312.08821.pdf) [3](https://arxiv.org/pdf/2312.09805.pdf), [4](https://arxiv.org/pdf/2306.04199.pdf) [5](https://arxiv.org/pdf/2305.06746.pdf) [6](https://arxiv.org/pdf/2309.05433.pdf) [7](https://arxiv.org/pdf/2312.06664.pdf) [8](https://arxiv.org/pdf/2311.12843.pdf) [9](https://arxiv.org/pdf/2312.09364.pdf) [10](https://arxiv.org/pdf/2312.07192.pdf) [11](https://arxiv.org/pdf/2312.09970.pdf). None of them followed the exact guidelines. If an author wants to use actually display a flag, then they always have the ability to write something like that in a custom acknowledgements section. Nobody does it in reality, but maybe they do it on posters and signs.

**Comment by jwbos** [comment]
On ePrint quite some papers do follow the EU rules (see for example: https://eprint.iacr.org/2018/687.pdf). 
Let me try and make an extension for `\addfunding` and then we can review how to improve this even further.

**Comment by jwbos** [comment]
I just pushed a first attempts in 167b2e69426f45923267df4bfed0592055733aa8 (note that the documentation needs to be updated). Please have a look if this is the functionality we want. 
One can now use a `text` option to provide the test to be displayed (multiple texts get concatenated) in a dedicated "Funded Acknowledgement" section at the end of the paper (before the References). There is a `mode` option which can only be EU to display the EU flag as required by the EU rules. This has been tested with both bibtex and biblatex. 
A full example would be:

```
\addfunding[country  = {europe},
            grantid  = {H2020-ICT-2014-1 644209},
            fundref  = {100010661},
            text     = {The research leading to these results has received funding
                        from the European Union's Horizon 2020 research and innovation
                        programme with contract H2020-ICT-2014-1 644209 HEAT.},
            mode = {EU},
           ]{Horizon 2020 Framework Programme}
```

**Comment by kmccurley** [comment]
(I probably should have known to check **YOUR** papers in eprint to see a flag).

I had apparently checked out a version from a previous commit. I downloaded yours now and tried it. There are definitely some good things about it.

1. you allow the author to customize the text for a grant acknowledgement, and you export it to the .meta file. Theoretically this means we can use it on the website as well.
2. it shows how to satisfy the Horizon Europe requirement with the EU flag (but we pick up a dependency that should only exist if mode=EU is turned on).

On the other hand, there are a couple of problems I can see.
1. Sometimes people want an "acknowledgements" section that combines their funding but also thanks the referee, or some other non-author, or an institution that hosted them. It would be really weird if someone put that in their paper and it showed up on the web as "Funding". It's also clumsy to have two acknowledgements sections in the paper but it feels a little wrong to mix them in a structured format.
2. I've become very skeptical of the "mode" parameter. I noticed that if a project is funded by both ERC and Horizon Europe, they want grant recipients to use [_two_ logos](https://erc.europa.eu/manage-your-project/communicate-your-research) including the one from ERC. If there is funding from the Australian Defence Force then they also want [their logo](https://www.researchgrants.gov.au/grant-announcements-outcomes/acknowledgement-funding-logo-use/acknowledgement-defence) and the ARC also wants [their logo](https://www.arc.gov.au/acknowledging-arc) and Canada's NFRF [wants theirs](https://www.sshrc-crsh.gc.ca/funding-financement/nfrf-fnfr/acknowledging-mention-eng.aspx). This could quickly get out of control, and we can't accommodate all these logos on the website. I don't see any problem with people fiddling to put what they want in their paper (as you did with the flag), but I don't think we need to provide support for every variation in the cls file. We just happen to be most familiar with the Horizon Europe requirement, but that may disappear anyway.
3. if we concatenate the `text` arguments on `\addfunding` together, it results in a clumsily written section. Most acknowledgement sections are written so that they flow together, with "and" in the right places.

I actually created my own solution to this problem, but I'm also not happy with that. I've attached the `iacrdoc.pdf` that describes it). The code is quite simple, and there is at least one thing we can use to make sure it works with biblatex:
```
\AddToHook{env/thebibliography/before}{\IACR@fundingstatement}   % for bibtex
\AddToHook{cmd/printbibliography/before}{\IACR@fundingstatement} % for biblatex
```
We should also hide the funding statement if the paper is anonymous. [iacrdoc.pdf](https://github.com/IACR/latex/files/13724214/iacrdoc.pdf)

The proposal I made is to automatically generate 
```
\section*{Funding Acknowledgements}

This work was supported by the Wellcome Trust [grant numbers xxxx, yyyy]; 
the Natural Environment Research Council [grant number zzzz]; 
and the Economic and Social Research Council [grant number aaaa].
```
This is similar to what [sage publishing](https://us.sagepub.com/en-us/nam/funding-acknowledgements) proposed. I also added a `\fundingstatement{full latex}` that allows authors full control over the funding section.

That way:
1. the default case is to generate a very compact paragraph.
2. we don't have a dependency on euflag and we don't need a special case for Horizon Europe
3. the author can generate whatever acknowledgements section they want, including mention of a referee or an advisor or whatever markup they want. If there are more than one grant (as there often is), then they can generate a multi-paragraph version, or a version with the flag on the right, or specific wording for the other grant. The [Office of Naval Research](https://ras.mit.edu/grant-and-contract-administration/managing-projects/federal-terms-and-conditions/sponsor-specific-terms/office-naval-research-onr) requires a statement like _"Any opinions, findings, and conclusions or recommendations expressed in this material are those of the author(s) and do not necessarily reflect the views of the Office of Naval Research.”_ 

One downside to my approach is that it doesn't attempt to transport anything to the web to comply with all the requirements of a funder.

I'm not sure that modes are really good to support. Sage Publishing wants authors to [say if they received no specific funding](https://us.sagepub.com/en-us/nam/funding-acknowledgements) for their research. Maybe we should support a `mode={unsupported}` and add this to the website:
![image](https://github.com/IACR/latex/assets/14105363/c988ada0-5e03-4278-91cf-9726b0b13084)

(I couldn't resist the joke). 

I think in retrospect that maybe we shouldn't have funding information on the web, and let authors deal with their own acknowledgements section. We could capture a text version of that in the meta file like the abstract, and show it on the web (provided they don't use any macros). Ideally we'd like to have a full HTML version of the paper on the web that's consistent with the PDF, but that's not a feasible thing to do automatically. Maybe it's better to just not show the funding on the web.

**Comment by jwbos** [comment]
Let's discuss in our call this evening. I am fine by not extending the `\addfunding` and put the control fully in the authors hands (since all functionality we offer will never satisfy exactly all the different requirements). The idea was to give the majority of people a nice helper function but if people wanted more sophisticated solutions they can do this themselves.

**Comment by kmccurley** [comment]
In the end I think we decided not to do this, for two reasons:
1. it's too complicated to be consistent between what's in the paper and what's on the web.
2. authors may want other things in their acknowledgements section.
