### ISSUE TITLE
Special characters in \href

### ISSUE THREAD

**Issue by jwbos** [IACR/latex#230]
It was reported that authorlinks containing characters with a special meaning in LaTeX can render incorrectly.
For example using addaythor with

`onclick  = {https://www.joppebos.com/~1/},`

renders into:

`https://www.joppebos.com//protect%20/unhbox%20/voidb@x%20/protect%20/penalty%20/@M%20/%20%7B%7D1/`

Other characters such as "%" or "#" will simply cause an LaTeX error.

We could try and detect the usage of ~ and replace this with \string~. However, if the author supplied \string~ (or one of the many alternatives in LaTeX to fix this) and we replace then we introduce an error. 

Question: Should we try and fix this in our class file or should we leave this to the author and provide more instructions how this can done correctly in the documentation?

**Comment by jwbos** [comment]
One way of trying to address is to redine the behaviour of tilde locally using:

**Comment by kmccurley** [comment]
Some people [say](https://jkorpela.fi/tilde.html#:~:text=If%20used%20in%20Web%20addresses,defined%2C%20universally%20working%20alternatives%20exist.) that `%7E` should be used in place of `~` in URLs anyway. Perhaps we should just give advice in iacrdoc to URL-encode any characters that are special characters in LaTeX, including `~_#$%&^{}\` Because % is a special character in LaTeX, you would do this with 
```
onclick = {https://crypto.stanford.edu/\%7Edabo}
```
The same is true for UTF-8 characters in URLs; see [google best practices](https://developers.google.com/search/docs/crawling-indexing/url-structure). Unfortunately it appears that different PDF viewers will display different behavior on URLs from `\href`.

**Comment by jwbos** [comment]
Ok, I will update the documentation. One can use `\string~` which should work in all PDF viewers but I will run some experiments.

**Comment by jwbos** [comment]
I explained this better in 9c647c3e7f04de75d3ff50e9f36c15cbfb10880a. Feel free to improve the text further.
