### ISSUE TITLE
"and" in list of authors

### ISSUE THREAD

**Issue by kmccurley** [IACR/latex#239]
I converted a paper today that had six authors, and the list of authors had an " and " in the wrong place:
![image](https://github.com/IACR/latex/assets/14105363/ff68e7f5-df53-499f-a2e7-b42fb1f9ff67)

**Comment by kmccurley** [comment]
There is something else troubling about this example: the vertical space between the title and the author block is too small.

**Comment by jwbos** [comment]
And the list starts with a ",": I will investigate this asap.

**Comment by jwbos** [comment]
I had a look at the LaTeX code and ran some tests. 
The problem *not* that this paper has multiple (six) authors. If we use a large number of authors in our template everything works.
Both the spacing and the incorrect display of authors is caused by the inclusion of [authblk](http://mirrors.ctan.org/macros/latex/contrib/preprint/authblk.pdf) . The package redefines `\author` (among other things) and really messes up our style file and layout. We should probably remove support for this package in our Docker since this should not be used.

**Comment by kmccurley** [comment]
I confirm that the problem was caused by the inclusion of authblk. I will remove it in our Dockerfile. The paper in question is one of those that just copies a lot of boilerplate `\usepackage` and other macros without regard to whether they conflict with the journal style. I had other problems with it from colors and comments.
